name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATIC_SITE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/web"
          api_location: ""
          output_location: "/out"
        env:
          IS_STATIC_EXPORT: true
      - run: dotnet build -c Release api/RhinoPackages.Api.csproj
      - uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "rhinopackages"
          package: "artifacts/bin/RhinoPackages.Api/release"
          publish-profile: ${{ secrets.FUNCTIONAPP_PROFILE }}
